// =====================================================================
// LabT1078 전용 데이터 파일 — HMR 안정화를 위해 LabT1078.jsx에서 분리
// Icons + i18n (다국어) 포함
// ※ JSX 문법 포함 → 반드시 .jsx 확장자 사용
// =====================================================================

import React from 'react';

// =====================================================================
// 아이콘 세트
// =====================================================================
export const Icons = {
  Play:     () => <svg viewBox="0 0 24 24" className="w-5 h-5 md:w-7 md:h-7" fill="currentColor"><path d="M6 4l15 8-15 8z"/></svg>,
  Pause:    () => <svg viewBox="0 0 24 24" className="w-5 h-5 md:w-7 md:h-7" fill="currentColor"><path d="M6 4h4v16H6zm8 0h4v16h-4z"/></svg>,
  Prev:     () => <svg viewBox="0 0 24 24" className="w-5 h-5 md:w-6 md:h-6" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M15 18l-6-6 6-6"/></svg>,
  Next:     () => <svg viewBox="0 0 24 24" className="w-5 h-5 md:w-6 md:h-6" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M9 18l6-6-6-6"/></svg>,
  Reset:    () => <svg viewBox="0 0 24 24" className="w-4 h-4 md:w-5 md:h-5" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 12"/><path d="M3 5v7h7"/></svg>,
  VolumeOn: () => <svg viewBox="0 0 24 24" className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><path d="M19.07 4.93a10 10 0 0 1 0 14.14M15.54 8.46a5 5 0 0 1 0 7.07"></path></svg>,
  VolumeOff:() => <svg viewBox="0 0 24 24" className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><line x1="23" y1="9" x2="17" y2="15"></line><line x1="17" y1="9" x2="23" y2="15"></line></svg>,
  Windows:  () => <svg viewBox="0 0 24 24" className="w-4 h-4" fill="#00a4ef"><path d="M0 3.449L9.75 2.1v8.969H0V3.449zm10.569-1.5L24 0v10.4H10.569V1.949zM0 11.85h9.75v8.969L0 19.47v-7.62zm10.569 0H24V24l-13.431-1.901V11.85z"/></svg>,
  Terminal: () => <svg viewBox="0 0 24 24" className="w-4 h-4 md:w-5 md:h-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="4 17 10 11 4 5"></polyline><line x1="12" y1="19" x2="20" y2="19"></line></svg>,
  Shield:   () => <svg viewBox="0 0 24 24" className="w-4 h-4 md:w-5 md:h-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>,
  Cursor:   () => <svg viewBox="0 0 24 24" className="w-6 h-6 md:w-8 md:h-8" fill="white" stroke="black" strokeWidth="1.5"><path d="M5.5 3.21V20.8c0 .45.54.67.85.35l4.86-4.86a.5.5 0 0 1 .35-.15h6.42c.45 0 .67-.54.35-.85L6.35 2.85a.5.5 0 0 0-.85.35z"></path></svg>,
  Activity: () => <svg viewBox="0 0 24 24" className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline></svg>,
  File:     () => <svg viewBox="0 0 24 24" className="w-3 h-3 md:w-4 md:h-4" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>,
  Download: () => <svg viewBox="0 0 24 24" className="w-5 h-5 md:w-6 md:h-6" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>,
  EventLog: () => <svg viewBox="0 0 24 24" className="w-4 h-4 md:w-5 md:h-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="9" y1="3" x2="9" y2="21"></line></svg>,
};

// =====================================================================
// 다국어 데이터 풀버전 (i18n) — 5개 언어 지원 (ko/en/zh/hi/ja)
// =====================================================================
export const i18n = {
  ko: {
    langCode: 'ko-KR',
    ui: {
      configTitle: "모의훈련 환경 설정", configSub: "입력한 정보가 터미널 환경에 동기화됩니다.", userLabel: "피해자 이름", corpLabel: "타겟 회사명", startBtn: "훈련 시작하기",
      hackerView: "💻 피해자 PC", defenderView: "🛡️ 방어자 SOC", step1: "👤 침투", step2: "🔍 정찰", step3: "🔑 탈취", step4: "👑 장악",
      what: "상황 설명", why: "전문가 인사이트", termsLabel: "핵심 용어 및 도구", complete: "훈련 완료 🎉", resetBtn: "초기화 및 재설정", socTitle: "🛡️ SOC 실시간 알럿", downloadCert: "수료증 PDF 다운로드",
      state0: "해커 침투 연출 중...", stateWaitTTS: "음성 대기 중...", statePlay: (t) => `다음 단계까지 ${t}초...`, statePause: "일시정지됨", completeMsg: (u, c) => `${u}님, ${c} 인프라 방어 훈련을 마쳤습니다.`, topoMap: "실시간 횡적 이동 추적",
      cert: { title: "수 료 증", subtitle: "증명 대상:", desc: "위 사람은 다음의 고급 위협 시뮬레이션 및 방어 훈련 과정을 성공적으로 수료하였습니다.", date: "발급일자", instructor: "수석 훈련관" },
      warning: "⚠️ 경고: 본 훈련에 포함된 해킹 도구 및 기법은 오직 '보안 교육 및 방어 훈련' 목적으로만 제공됩니다. 불법적인 사용에 대한 책임은 전적으로 본인에게 있습니다.",
      agreeText: "위의 법적 고지 및 책임 소재를 완전히 이해하였으며 이에 동의합니다."
    },
    texts: [
      { title: "사건의 발단", feynman: "직원이 무심코 연 피싱 메일 한 장이 성문을 열어주는 스위치였죠. 악성코드가 실행되며 해커의 원격 제어 터미널이 열립니다.", expert: "스피어 피싱을 통한 Initial Access. 공격자는 피해자의 데스크톱 환경(RDP/VNC)을 제어할 준비를 마쳤습니다.", defTooltip: "👀 백그라운드에서 알 수 없는 외부 IP의 원격 접속 트래픽이 감지되었습니다.", terms: [ { name: "Spear Phishing", desc: "특정 대상을 겨냥해 악성 첨부파일이나 링크를 보내는 맞춤형 이메일 공격 기법" }, { name: "C2 Server", desc: "해커가 감염된 PC를 원격으로 조종하고 명령을 내리는 중앙 통제 서버" } ] },
      { title: "초기 침투", feynman: "침입자가 거울을 봅니다. '내가 지금 평민 옷을 입고 있나, 장군 옷을 입고 있나?' 자신의 현재 권한(계정)을 파악하는 거죠.", expert: "획득한 세션의 권한(Privilege)과 소속 그룹을 식별하여 권한 상승 벡터를 수립합니다.", defTooltip: "⚠️ 일반 사용자가 시스템 권한을 묻는 수상한 명령어(whoami /all)를 실행했습니다.", hackerLog: { title: "whoami_priv_check.txt", lines: [ { log: "USER INFORMATION\n----------------\nUser Name: CORP\\Alice", desc: "💡 현재 내가 탈취한 계정의 신분을 확인합니다." }, { log: "GROUP INFORMATION\n...\nBUILTIN\\Users", desc: "💡 내가 속한 그룹을 확인하여 어디까지 접근 가능한지 파악합니다." }, { log: "PRIVILEGES INFORMATION\n...\nSeChangeNotifyPrivilege", desc: "💡 관리자 권한을 뺏기 위해 악용할 수 있는 틈새 권한이 있는지 살핍니다." } ] }, terms: [ { name: "whoami /all", desc: "현재 로그인한 사용자의 계정명, 소속 그룹, 보유 권한을 모두 출력하는 윈도우 명령어" }, { name: "Privilege Escalation", desc: "일반 사용자 권한을 시스템 최고 관리자 권한으로 상승시키는 해킹 단계" } ] },
      { title: "내부망 정찰", feynman: "성을 털려면 지도가 필요하죠. 해커가 나침반과 지도를 꺼내 왕(중앙 서버)이 사는 성의 위치를 확인합니다.", expert: "서브넷 대역과 DNS(보통 도메인 컨트롤러) IP를 파악하여 타겟의 네트워크 위치를 확보합니다.", defTooltip: "🔍 내부망 IP와 DNS 서버 정보를 탐색하는 네트워크 스캔 징후가 보입니다.", hackerLog: { title: "network_recon.txt", lines: [ { log: "IPv4 Address. . . . . . : 192.168.10.45", desc: "💡 현재 밟고 있는 피해자 PC의 내부 IP 주소입니다." }, { log: "Default Gateway . . . . : 192.168.10.1", desc: "💡 밖으로 나갈 수 있는 통로를 확인합니다." }, { log: "DNS Servers . . . . . . : 192.168.10.10", desc: "💡 사내망에서 DNS 서버는 보통 '도메인 컨트롤러(왕)'입니다. 타겟 발견!" } ] }, terms: [ { name: "ipconfig /all", desc: "PC의 IP, 게이트웨이, DNS 서버 등 모든 네트워크 설정을 확인하는 명령어" }, { name: "Domain Controller", desc: "회사 네트워크의 모든 계정과 권한을 중앙 통제하는 핵심 서버 (왕좌)" } ] },
      { title: "공격 경로 탐색", feynman: "수만 명의 주민들을 조사해 족보를 만듭니다! 왕에게 다가갈 수 있는 가장 빠르고 은밀한 개구멍을 찾는 과정이죠.", expert: "BloodHound를 사용해 Active Directory 내 객체 간의 권한 관계(ACL, 세션)를 시각화합니다.", defTooltip: "🚨 짧은 시간에 막대한 양의 Active Directory 정보 조회(LDAP)가 발생했습니다!", hackerLog: { title: "SharpHound_Log_Analyzer.txt", lines: [ { log: "[+] Enumerating trusts for domain...", desc: "💡 사내망 시스템 간의 신뢰 관계(권한 연결고리) 파악 중" }, { log: "[+] Collecting Local Admin, Sessions...", desc: "💡 각 PC의 관리자 권한 및 현재 로그인한 직원 세션 수집 (징검다리 탐색)" }, { log: "[+] Found 1500 Computers, 500 Users.", desc: "💡 사내 전체 조직도와 인프라 권한 정보 확보 완료!" }, { log: "[+] Compressing data to BloodHound.zip", desc: "💡 수집한 거대한 '권한 지도'를 단 하나의 zip 파일로 압축하여 반출 준비" } ] }, terms: [ { name: "SharpHound.exe", desc: "도메인 내 수만 대의 PC와 사용자 간의 권한(AD) 관계를 싹쓸이하여 수집하는 정찰 도구" }, { name: "BloodHound", desc: "수집한 zip 데이터를 바탕으로 최고 관리자까지 가는 '최단 공격 경로'를 그려주는 시각화 툴" } ] },
      { title: "타겟 식별", feynman: "아킬레스건 발견! 문지기 로봇(서비스 계정)이 실수로 마스터 키를 차고 있는 걸 찾아냈습니다.", expert: "비밀번호가 자주 바뀌지 않고 과도한 권한(Domain Admin)이 부여된 서비스 계정을 식별했습니다.", defTooltip: "🎯 취약한 서비스 계정을 향한 비정상적인 접근 패턴을 주시하고 있습니다.", hackerLog: { title: "attack_path_analysis.txt", lines: [ { log: "Node 1: USER Alice@corp.local", desc: "💡 현재 장악한 시작점(Alice의 PC)입니다." }, { log: "Node 2: GROUP IT_Support [MemberOf]", desc: "💡 Alice가 IT 지원팀에 속해 있다는 권한 고리를 발견했습니다." }, { log: "Node 3: USER SVC_SQL [AdminTo]", desc: "💡 IT 지원팀이 SVC_SQL 서비스 계정을 관리할 수 있음을 알아냈습니다. 타겟 확정!" } ] }, terms: [ { name: "Service Account", desc: "사람이 아닌 시스템이나 애플리케이션이 자동화 작업을 위해 사용하는 계정 (관리가 소홀함)" }, { name: "Domain Admin", desc: "도메인 내의 모든 컴퓨터와 서버를 통제할 수 있는 최고 관리자 권한" } ] },
      { title: "Kerberoasting", feynman: "해커가 당당하게 경비병에게 걸어가 '저기, 로봇 문지기랑 얘기하게 출입증 좀 줘'라고 속입니다. 정상적인 절차라 모두가 속아 넘어갑니다.", expert: "Kerberos TGS 요청은 정상적인 인증 프로세스이므로 기존 방화벽을 무사히 통과할 수 있습니다.", defTooltip: "⚠️ Event ID 4769: 해당 사용자가 비정상적인 서비스 티켓(TGS)을 발급받았습니다.", hackerLog: { title: "kerberoast_request.txt", lines: [ { log: "[*] Action: Kerberoasting", desc: "💡 중앙 서버에 SVC_SQL 계정과 통신하고 싶다며 '합법적인 출입증'을 요구합니다." }, { log: "[*] Target User : SVC_SQL", desc: "💡 보안이 허술한 타겟을 정확히 짚어서 서버를 속이는 중입니다." } ] }, terms: [ { name: "Kerberoasting", desc: "취약한 서비스 계정의 인증 티켓을 몰래 발급받아, 오프라인에서 암호를 크랙하는 공격 기법" }, { name: "TGS (Ticket Granting Service)", desc: "특정 서비스에 접근할 수 있도록 권한을 증명해주는 합법적인 출입증(티켓)" } ] },
      { title: "티켓 탈취", feynman: "경비병이 굳게 잠긴 금고(출입증)를 줍니다. 이 안에는 로봇 문지기의 진짜 비밀번호가 암호화되어 들어있죠.", expert: "서비스 계정의 NTLM 해시로 암호화된 TGS 티켓을 메모리에서 성공적으로 추출했습니다.", defTooltip: "📦 서버가 정상적인 인증 티켓을 발급했습니다. 아직 명확한 시스템 파괴 행위는 없습니다.", hackerLog: { title: "hash_extracted.txt", lines: [ { log: "[+] Ticket successfully extracted!", desc: "💡 서버가 아무런 의심 없이 암호화된 티켓을 내어주었습니다." }, { log: "[+] Hash: $krb5tgs$23$*SVC_SQL$...", desc: "💡 이 해시(Hash) 값 안에 타겟 계정의 진짜 비밀번호가 숨겨져 있습니다." } ] }, terms: [ { name: "NTLM Hash", desc: "윈도우가 사용자의 비밀번호를 보호하기 위해 암호화(해싱)하여 저장하는 데이터 형태" }, { name: "Memory Extraction", desc: "보안 솔루션 몰래 시스템 메모리(RAM)에 직접 접근해 암호화된 인증 정보를 빼내는 기법" } ] },
      { title: "오프라인 크래킹", feynman: "해커는 이 금고를 자기 집 지하실로 몰래 가져갑니다. 사내 CCTV를 피해 슈퍼컴퓨터로 수억 개의 열쇠를 마구 꽂아보는 거죠.", expert: "사내망 관제를 벗어나 해커의 개인 장비로 Brute-force 공격을 수행하므로 내부에선 탐지되지 않습니다.", defTooltip: "🔇 (탐지 불가) 해커가 사내망을 벗어나 오프라인에서 암호를 해독 중입니다...", hackerLog: { title: "offline_cracking.txt", lines: [ { log: "Session..........: hashcat\nStatus...........: Running", desc: "💡 훔쳐온 해시를 해커의 강력한 그래픽카드(GPU)로 해독하기 시작합니다." }, { log: "Speed.Dev.#1.....: 25000 kH/s", desc: "💡 1초에 수천만 번씩 비밀번호를 대입하는 중입니다. 회사 밖이라 탐지조차 되지 않습니다." } ] }, terms: [ { name: "Hashcat", desc: "그래픽 카드(GPU)의 엄청난 연산력을 이용해 암호 해시를 매우 빠른 속도로 풀어내는 도구" }, { name: "Brute-force", desc: "비밀번호가 풀릴 때까지 무식하게 가능한 모든 문자 조합을 계속 대입해보는 공격" } ] },
      { title: "암호 해독 완료", feynman: "찰칵! 문지기가 '1234' 같은 허술한 자물쇠를 쓴 덕분에 금고가 열렸습니다. 이제 마스터 키는 해커의 손에 있습니다.", expert: "복잡성이 떨어지는 패스워드 정책의 허점을 찔러 강력한 평문 인증 정보를 손에 넣었습니다.", defTooltip: "🔇 (탐지 불가) 암호가 뚫렸지만 시스템 내부에는 로그인 실패 로그가 전혀 남지 않았습니다.", hackerLog: { title: "cracked_password.txt", lines: [ { log: "$krb5tgs$23$*SVC_SQL$...:P@ssword123!", desc: "💡 빙고! 타겟이 너무 뻔한 비밀번호를 사용한 덕분에 자물쇠가 풀렸습니다." }, { log: "[+] Cracking completed successfully.", desc: "💡 막강한 권한을 가진 계정의 비밀번호를 완벽히 손에 넣었습니다." } ] }, terms: [ { name: "Plaintext Credential", desc: "암호화되지 않아 누구나 바로 읽고 시스템 로그인에 사용할 수 있는 평문 상태의 비밀번호" }, { name: "Password Complexity", desc: "비밀번호에 대/소문자, 숫자, 특수문자를 강제로 섞어 크래킹을 어렵게 만드는 보안 규칙" } ] },
      { title: "도메인 장악", feynman: "해커가 획득한 마스터 키로 왕의 옥좌(도메인 컨트롤러)에 앉았습니다. 이제 이 성의 모든 컴퓨터는 해커의 마음대로 움직입니다.", expert: "탈취한 Domain Admin 권한으로 도메인 컨트롤러(DC)에 원격(WinRM) 접속하여 인프라를 장악합니다.", defTooltip: "🚨 치명적 위험! 일반 PC IP에서 도메인 컨트롤러(DC)로 최고 관리자 원격 접속이 시도되었습니다!", hackerLog: { title: "domain_takeover.txt", lines: [ { log: "[*] Connecting to 192.168.10.10 (DC01)", desc: "💡 알아낸 비밀번호로 회사의 최고 서버인 '도메인 컨트롤러'에 원격 접속합니다." }, { log: "[+] Successful login! Session established.", desc: "💡 접속 성공! 이제 회사의 모든 PC와 서버가 해커의 발밑에 있습니다." } ] }, terms: [ { name: "WinRM / evil-winrm", desc: "윈도우 원격 관리 프로토콜을 악용해 시스템에 원격 셸(명령창)을 띄우는 해킹 툴" }, { name: "Lateral Movement (횡적 이동)", desc: "해커가 침투한 최초 PC에서 멈추지 않고, 내부망의 다른 서버나 관리자 PC로 침투를 확장하는 행위" } ] },
      { title: "방어 가동", feynman: "하지만 성의 비밀 암행어사(GOTROOT)가 지켜보고 있었습니다! 해커가 왕좌에 앉으려는 순간, 포승줄을 던져 통신을 끊고 밖으로 쫓아냅니다.", expert: "보안 관제 시스템이 횡적 이동을 탐지하여, 방화벽 IP 차단 및 계정 비활성화 조치를 실시간으로 수행했습니다.", defTooltip: "🛡️ 자동 방어 가동: 방화벽 정책을 업데이트하여 해당 IP를 완벽히 차단 및 격리했습니다.", hackerLog: { title: "connection_terminated.txt", lines: [ { log: "FATAL ERROR: Connection forcefully closed", desc: "💡 방어 시스템(EDR/SIEM)이 비정상 행위를 감지하고 즉시 연결을 강제 폭파시켰습니다." }, { log: "IP 192.168.10.45 has been isolated.", desc: "💡 감염된 PC가 사내망에서 완벽히 격리되며 방어에 성공했습니다!" } ] }, terms: [ { name: "EDR & SIEM", desc: "PC의 위협을 탐지하는 솔루션(EDR)과 전사적 보안 로그를 모아 연관 분석하는 중앙 시스템(SIEM)" }, { name: "Network Isolation", desc: "감염된 PC가 다른 내부 시스템과 통신하며 바이러스를 퍼뜨리지 못하도록 네트워크를 강제 차단하는 조치" } ] }
    ]
  },
  en: {
    langCode: 'en-US',
    ui: {
      configTitle: "Simulation Setup", configSub: "Info will be synced with the terminal.", userLabel: "Victim Name", corpLabel: "Company Name", startBtn: "Start Training",
      hackerView: "💻 Victim PC", defenderView: "🛡️ Defender SOC", step1: "👤 Access", step2: "🔍 Recon", step3: "🔑 Theft", step4: "👑 Pwned",
      what: "Scenario", why: "Expert Insight", termsLabel: "Key Terms & Tools", complete: "Training Complete 🎉", resetBtn: "Restart Setup", socTitle: "🛡️ SOC Live Alert", downloadCert: "Download PDF Certificate",
      state0: "Infiltrating...", stateWaitTTS: "Audio playing...", statePlay: (t) => `Next in ${t}s.`, statePause: "Paused", completeMsg: (u, c) => `Congrats ${u}! You secured ${c}.`, topoMap: "Lateral Movement Tracker",
      cert: { title: "Certificate of Completion", subtitle: "This proudly certifies that", desc: "has successfully completed the advanced threat simulation and defense training module:", date: "Date of Issue", instructor: "Lead Instructor" },
      warning: "⚠️ WARNING: Educational use only. The user bears all legal responsibility for any misuse.",
      agreeText: "I agree to this legal disclaimer."
    },
    texts: [
      { title: "Initial Access", feynman: "A single phishing email was the switch that opened the castle gates. The employee clicked without thinking, and the attacker's remote terminal silently sprang to life.", expert: "Initial Access via Spear Phishing. The attacker now controls the victim's desktop environment (RDP/VNC).", defTooltip: "👀 Background remote access traffic from an unknown external IP detected.", hackerLog: null, terms: [ {name:"Spear Phishing", desc:"Targeted email attack with malicious attachments or links aimed at a specific individual."}, {name:"C2 Server", desc:"Command & Control server used by attackers to remotely control infected PCs."} ] },
      { title: "Initial Infiltration", feynman: "The intruder looks in a mirror. 'Am I wearing a commoner's clothes or a general's armor?' They're figuring out their current level of access.", expert: "Identifying the privilege level and group memberships of the compromised session to establish privilege escalation vectors.", defTooltip: "⚠️ A regular user executed a suspicious command (whoami /all) to query system privileges.", hackerLog: { title: "whoami_priv_check.txt", lines: [ { log: "USER INFORMATION\n----------------\nUser Name: CORP\\Alice", desc: "💡 Checking the identity of the compromised account." }, { log: "GROUP INFORMATION\n...\nBUILTIN\\Users", desc: "💡 Reviewing group memberships to determine access scope." }, { log: "PRIVILEGES INFORMATION\n...\nSeChangeNotifyPrivilege", desc: "💡 Looking for exploitable privileges to escalate to admin." } ] }, terms: [ { name: "whoami /all", desc: "A Windows command that displays the current user's account name, groups, and all assigned privileges." }, { name: "Privilege Escalation", desc: "The hacking phase where a regular user account is elevated to the highest system administrator privileges." } ] },
      { title: "Internal Recon", feynman: "To storm a castle, you need a map. The hacker pulls out a compass and map to locate the king's castle — the central server.", expert: "Identifying subnet ranges and DNS (typically the Domain Controller) IP to map the target's network topology.", defTooltip: "🔍 Network scanning detected — internal IP and DNS server information being probed.", hackerLog: { title: "network_recon.txt", lines: [ { log: "IPv4 Address. . . . . . : 192.168.10.45", desc: "💡 The victim PC's internal IP address on the corporate network." }, { log: "Default Gateway . . . . : 192.168.10.1", desc: "💡 Discovering the gateway — the exit route from the network." }, { log: "DNS Servers . . . . . . : 192.168.10.10", desc: "💡 In corporate networks, the DNS server is usually the Domain Controller (the king). Target found!" } ] }, terms: [ { name: "ipconfig /all", desc: "A command that shows a PC's IP, gateway, DNS server, and all network configuration settings." }, { name: "Domain Controller", desc: "The core server that centrally manages all accounts and permissions in a company network — the throne." } ] },
      { title: "Attack Path Discovery", feynman: "Investigating tens of thousands of residents to build a family tree! Finding the fastest, stealthiest path to reach the king.", expert: "Using BloodHound to visualize permission relationships (ACLs, sessions) between objects in Active Directory.", defTooltip: "🚨 Massive volume of Active Directory queries (LDAP) detected in a short time span!", hackerLog: { title: "SharpHound_Log_Analyzer.txt", lines: [ { log: "[+] Enumerating trusts for domain...", desc: "💡 Mapping trust relationships (permission chains) between domain systems." }, { log: "[+] Collecting Local Admin, Sessions...", desc: "💡 Collecting local admin rights and logged-in sessions across all PCs (finding stepping stones)." }, { log: "[+] Found 1500 Computers, 500 Users.", desc: "💡 Full organizational chart and infrastructure permissions map acquired!" }, { log: "[+] Compressing data to BloodHound.zip", desc: "💡 Compressing the massive permission map into a single zip file for exfiltration." } ] }, terms: [ { name: "SharpHound.exe", desc: "A recon tool that sweeps all permission relationships (AD) between thousands of PCs and users in a domain." }, { name: "BloodHound", desc: "A visualization tool that maps the shortest attack path to Domain Admin using collected data." } ] },
      { title: "Target Identified", feynman: "Achilles' heel found! The robot guard (service account) was unknowingly carrying the master key all along.", expert: "Identified a service account with an outdated password and excessive privileges (Domain Admin).", defTooltip: "🎯 Monitoring abnormal access patterns targeting a vulnerable service account.", hackerLog: { title: "attack_path_analysis.txt", lines: [ { log: "Node 1: USER Alice@corp.local", desc: "💡 Our current foothold — Alice's compromised PC." }, { log: "Node 2: GROUP IT_Support [MemberOf]", desc: "💡 Discovered that Alice belongs to the IT Support group — a permission link." }, { log: "Node 3: USER SVC_SQL [AdminTo]", desc: "💡 IT Support can manage the SVC_SQL service account. Target confirmed!" } ] }, terms: [ { name: "Service Account", desc: "An account used by systems or applications for automated tasks — often poorly managed and overlooked." }, { name: "Domain Admin", desc: "The highest-level administrator privileges that can control all computers and servers in a domain." } ] },
      { title: "Kerberoasting", feynman: "The hacker boldly walks up to the guard: 'Hey, I need a pass to talk to the robot gatekeeper.' It's a legitimate procedure, so everyone falls for it.", expert: "A Kerberos TGS request is a normal authentication process, so it passes through existing firewalls undetected.", defTooltip: "⚠️ Event ID 4769: This user was issued an abnormal service ticket (TGS).", hackerLog: { title: "kerberoast_request.txt", lines: [ { log: "[*] Action: Kerberoasting", desc: "💡 Requesting a 'legitimate pass' from the central server to communicate with SVC_SQL." }, { log: "[*] Target User : SVC_SQL", desc: "💡 Precisely targeting the vulnerable account to deceive the server." } ] }, terms: [ { name: "Kerberoasting", desc: "An attack that secretly obtains authentication tickets of vulnerable service accounts and cracks passwords offline." }, { name: "TGS (Ticket Granting Service)", desc: "A legitimate ticket that proves authorization to access a specific service." } ] },
      { title: "Ticket Extracted", feynman: "The guard hands over a locked vault (the pass). Inside lies the robot gatekeeper's real password — encrypted.", expert: "Successfully extracted the TGS ticket encrypted with the service account's NTLM hash from memory.", defTooltip: "📦 The server issued a legitimate authentication ticket. No clear signs of malicious activity yet.", hackerLog: { title: "hash_extracted.txt", lines: [ { log: "[+] Ticket successfully extracted!", desc: "💡 The server handed over the encrypted ticket without any suspicion." }, { log: "[+] Hash: $krb5tgs$23$*SVC_SQL$...", desc: "💡 The target account's real password is hidden inside this hash value." } ] }, terms: [ { name: "NTLM Hash", desc: "An encrypted (hashed) data form that Windows uses to store and protect user passwords." }, { name: "Memory Extraction", desc: "A technique that directly accesses system memory (RAM) to steal encrypted credentials covertly." } ] },
      { title: "Offline Cracking", feynman: "The hacker smuggles the vault to their basement. Away from the company's cameras, they use a supercomputer to try hundreds of millions of keys.", expert: "Performing brute-force attacks on the hacker's personal hardware outside the corporate network — completely undetectable internally.", defTooltip: "🔇 (Undetectable) The hacker is cracking the password offline, outside the corporate network...", hackerLog: { title: "offline_cracking.txt", lines: [ { log: "Session..........: hashcat\nStatus...........: Running", desc: "💡 Beginning to crack the stolen hash using the hacker's powerful GPU." }, { log: "Speed.Dev.#1.....: 25000 kH/s", desc: "💡 Trying tens of millions of password combinations per second. Outside the network — completely undetectable." } ] }, terms: [ { name: "Hashcat", desc: "A tool that leverages GPU computing power to crack password hashes at extreme speeds." }, { name: "Brute-force", desc: "An attack that keeps trying every possible character combination until the password is cracked." } ] },
      { title: "Password Cracked", feynman: "Click! The gatekeeper used a flimsy lock like '1234', so the vault opens. The master key is now in the hacker's hands.", expert: "Exploited weak password policy to obtain plaintext credentials for a high-privilege account.", defTooltip: "🔇 (Undetectable) The password was cracked, but no failed login logs exist in the internal system.", hackerLog: { title: "cracked_password.txt", lines: [ { log: "$krb5tgs$23$*SVC_SQL$...:P@ssword123!", desc: "💡 Bingo! The target used a predictable password — the vault is open." }, { log: "[+] Cracking completed successfully.", desc: "💡 The password for a high-privilege account has been fully compromised." } ] }, terms: [ { name: "Plaintext Credential", desc: "An unencrypted password that can be directly read and used to log into systems." }, { name: "Password Complexity", desc: "Security rules that enforce mixing uppercase, lowercase, numbers, and special characters to resist cracking." } ] },
      { title: "Domain Takeover", feynman: "The hacker uses the master key to sit on the king's throne (Domain Controller). Now every computer in this castle bends to the hacker's will.", expert: "Remotely accessing the Domain Controller (DC) via WinRM with stolen Domain Admin credentials to seize full infrastructure control.", defTooltip: "🚨 CRITICAL! A Domain Admin remote access attempt from a regular PC IP to the Domain Controller detected!", hackerLog: { title: "domain_takeover.txt", lines: [ { log: "[*] Connecting to 192.168.10.10 (DC01)", desc: "💡 Using the cracked password to remotely access the company's top server — the Domain Controller." }, { log: "[+] Successful login! Session established.", desc: "💡 Login successful! Every PC and server in the company is now under the hacker's control." } ] }, terms: [ { name: "WinRM / evil-winrm", desc: "A hacking tool that exploits the Windows Remote Management protocol to open remote shells on target systems." }, { name: "Lateral Movement", desc: "The attacker's progression from the initial compromised PC to other servers and admin workstations across the network." } ] },
      { title: "Defense Activated", feynman: "But the castle's secret inspector (GOTROOT) was watching! Just as the hacker reaches for the throne, they throw a lasso — cutting communications and ejecting the intruder.", expert: "Security monitoring systems detected lateral movement and performed real-time firewall IP blocking and account deactivation.", defTooltip: "🛡️ Auto-defense activated: Firewall policies updated to completely block and isolate the attacker's IP.", hackerLog: { title: "connection_terminated.txt", lines: [ { log: "FATAL ERROR: Connection forcefully closed", desc: "💡 The defense system (EDR/SIEM) detected anomalous behavior and immediately terminated the connection." }, { log: "IP 192.168.10.45 has been isolated.", desc: "💡 The infected PC has been completely isolated from the network. Defense successful!" } ] }, terms: [ { name: "EDR & SIEM", desc: "Solutions for detecting endpoint threats (EDR) and a central system for aggregating and correlating security logs enterprise-wide (SIEM)." }, { name: "Network Isolation", desc: "Forcibly cutting an infected PC's network access to prevent malware from spreading to other internal systems." } ] }
    ]
  },
  hi: {
    langCode: 'hi-IN',
    ui: {
      configTitle: "सिमुलेशन सेटअप", configSub: "जानकारी टर्मिनल के साथ सिंक होगी।", userLabel: "पीड़ित का नाम", corpLabel: "कंपनी का नाम", startBtn: "प्रशिक्षण शुरू करें",
      hackerView: "💻 पीड़ित PC", defenderView: "🛡️ रक्षात्मक SOC", step1: "👤 पहुँच", step2: "🔍 रेकन", step3: "🔑 चोरी", step4: "👑 कब्ज़ा",
      what: "परिदृश्य", why: "विशेषज्ञ अंतर्दृष्टि", termsLabel: "प्रमुख शर्तें और उपकरण", complete: "प्रशिक्षण पूरा 🎉", resetBtn: "पुनः आरंभ करें", socTitle: "🛡️ SOC अलर्ट", downloadCert: "PDF प्रमाण पत्र डाउनलोड करें",
      state0: "घुसपैठ हो रही है...", stateWaitTTS: "ऑडियो चल रहा है...", statePlay: (t) => `अगला चरण ${t}s में।`, statePause: "रुका हुआ",
      completeMsg: (u, c) => `बधाई हो ${u}! आपने ${c} को सुरक्षित किया।`, topoMap: "थ्रेट ट्रैकर",
      cert: { title: "प्रमाणपत्र", subtitle: "यह प्रमाणित किया जाता है कि", desc: "ने उन्नत खतरे सिमुलेशन और रक्षा प्रशिक्षण मॉड्यूल को सफलतापूर्वक पूरा किया है:", date: "जारी करने की तिथि", instructor: "मुख्य प्रशिक्षक" },
      warning: "⚠️ चेतावनी: यह प्रशिक्षण केवल शैक्षिक उद्देश्यों के लिए है। किसी भी दुरुपयोग की जिम्मेदारी उपयोगकर्ता की होगी।",
      agreeText: "मैं इस कानूनी अस्वीकरण से सहमत हूँ।"
    },
    texts: [
      { title: "प्रारंभिक पहुँच", feynman: "कर्मचारी ने बेसुध होकर खोली एक फ़िशिंग ईमेल — यही वह स्विच थी जिसने किले का दरवाज़ा खोल दिया। मैलवेयर चला, और हमलावर का रिमोट टर्मिनल सक्रिय हो गया।", expert: "स्पियर फ़िशिंग के माध्यम से Initial Access। C2 सर्वर से कनेक्शन स्थापित हुआ।", defTooltip: "👀 अज्ञात बाहरी IP से रिमोट एक्सेस ट्रैफिक का पता चला।", hackerLog: null, terms: [{name:"Spear Phishing", desc:"किसी विशिष्ट व्यक्ति को निशाना बनाकर दुर्भावनापूर्ण अटैचमेंट या लिंक भेजने वाला लक्षित ईमेल हमला।"}, {name:"C2 Server", desc:"हमलावर द्वारा संक्रमित PC को दूरस्थ रूप से नियंत्रित करने और आदेश देने के लिए उपयोग किया जाने वाला केंद्रीय सर्वर।"}] },
      { title: "प्रारंभिक घुसपैठ", feynman: "घुसपैठिया शीशे में देखता है। 'क्या मैं आम नागरिक के कपड़ों में हूँ या जनरल की वर्दी में?' वह अपनी वर्तमान पहुँच का स्तर जानना चाहता है।", expert: "अपहृत सत्र की विशेषाधिकार स्तर और समूह सदस्यता की पहचान करना — विशेषाधिकार वृद्धि रणनीति बनाना।", defTooltip: "⚠️ एक सामान्य उपयोगकर्ता ने संदिग्ध कमांड (whoami /all) चलाकर सिस्टम अधिकारों की जाँच की।", hackerLog: { title: "whoami_priv_check.txt", lines: [ { log: "USER INFORMATION\n----------------\nUser Name: CORP\\Alice", desc: "💡 अपहृत खाते की पहचान की पुष्टि कर रहा है।" }, { log: "GROUP INFORMATION\n...\nBUILTIN\\Users", desc: "💡 समूह सदस्यता जाँचकर पहुँच सीमा निर्धारित कर रहा है।" }, { log: "PRIVILEGES INFORMATION\n...\nSeChangeNotifyPrivilege", desc: "💡 एडमिन तक पहुँच बढ़ाने के लिए शोषण योग्य विशेषाधिकार ढूँढ रहा है।" } ] }, terms: [ { name: "whoami /all", desc: "विंडोज कमांड जो वर्तमान उपयोगकर्ता का नाम, समूह और सभी विशेषाधिकार दिखाती है।" }, { name: "Privilege Escalation", desc: "हैकिंग चरण जहाँ सामान्य उपयोगकर्ता खाते को सर्वोच्च सिस्टम व्यवस्थापक अधिकारों तक बढ़ाया जाता है।" } ] },
      { title: "आंतरिक नेटवर्क टोही", feynman: "किले को लूटने के लिए नक्शा चाहिए। हैकर अपना कंपास और नक्शा निकालकर राजा (केंद्रीय सर्वर) के महल का स्थान खोजता है।", expert: "सबनेट रेंज और DNS (आमतौर पर Domain Controller) IP की पहचान करके लक्ष्य की नेटवर्क स्थिति को मैप करना।", defTooltip: "🔍 आंतरिक IP और DNS सर्वर जानकारी की खोज — नेटवर्क स्कैन के संकेत।", hackerLog: { title: "network_recon.txt", lines: [ { log: "IPv4 Address. . . . . . : 192.168.10.45", desc: "💡 पीड़ित PC का आंतरिक IP पता।" }, { log: "Default Gateway . . . . : 192.168.10.1", desc: "💡 नेटवर्क से बाहर जाने का मार्ग खोज रहा है।" }, { log: "DNS Servers . . . . . . : 192.168.10.10", desc: "💡 कॉर्पोरेट नेटवर्क में DNS सर्वर आमतौर पर Domain Controller (राजा) होता है। लक्ष्य मिला!" } ] }, terms: [ { name: "ipconfig /all", desc: "PC का IP, गेटवे, DNS सर्वर और सभी नेटवर्क सेटिंग्स दिखाने वाला कमांड।" }, { name: "Domain Controller", desc: "कंपनी नेटवर्क के सभी खातों और अनुमतियों का केंद्रीय प्रबंधन करने वाला मुख्य सर्वर (सिंहासन)।" } ] },
      { title: "हमले का मार्ग खोज", feynman: "दसों हज़ार निवासियों की जाँच करके वंशवृक्ष बनाना! राजा तक पहुँचने का सबसे तेज़ और गुप्त रास्ता खोजना।", expert: "Active Directory में वस्तुओं के बीच अनुमति संबंधों (ACL, सत्र) को BloodHound से विज़ुअलाइज़ करना।", defTooltip: "🚨 कम समय में Active Directory सूचना (LDAP) की भारी मात्रा में पूछताछ!", hackerLog: { title: "SharpHound_Log_Analyzer.txt", lines: [ { log: "[+] Enumerating trusts for domain...", desc: "💡 डोमेन प्रणालियों के बीच विश्वास संबंध (अनुमति श्रृंखला) मैप कर रहा है।" }, { log: "[+] Collecting Local Admin, Sessions...", desc: "💡 सभी PC पर स्थानीय व्यवस्थापक अधिकार और लॉग-इन सत्र एकत्र कर रहा है।" }, { log: "[+] Found 1500 Computers, 500 Users.", desc: "💡 पूरा संगठनात्मक चार्ट और इंफ्रास्ट्रक्चर अनुमति मानचित्र प्राप्त!" }, { log: "[+] Compressing data to BloodHound.zip", desc: "💡 विशाल अनुमति मानचित्र को एक zip फ़ाइल में संपीड़ित कर रहा है।" } ] }, terms: [ { name: "SharpHound.exe", desc: "डोमेन में हज़ारों PC और उपयोगकर्ताओं के बीच सभी अनुमति संबंधों (AD) को एकत्र करने वाला टोही उपकरण।" }, { name: "BloodHound", desc: "एकत्र किए गए डेटा से Domain Admin तक का सबसे छोटा हमला मार्ग मैप करने वाला विज़ुअलाइज़ेशन टूल।" } ] },
      { title: "लक्ष्य पहचाना गया", feynman: "एच्लीस की एड़ी मिली! रोबोट पहरेदार (सेवा खाता) लापरवाही से मास्टर चाबी लिए घूम रहा था।", expert: "पुराने पासवर्ड और अत्यधिक विशेषाधिकार (Domain Admin) वाले सेवा खाते की पहचान की।", defTooltip: "🎯 कमज़ोर सेवा खाते की ओर असामान्य पहुँच पैटर्न पर नज़र।", hackerLog: { title: "attack_path_analysis.txt", lines: [ { log: "Node 1: USER Alice@corp.local", desc: "💡 हमारा वर्तमान पैर जमाव — Alice का अपहृत PC।" }, { log: "Node 2: GROUP IT_Support [MemberOf]", desc: "💡 Alice IT सपोर्ट समूह से संबंधित है — अनुमति की कड़ी।" }, { log: "Node 3: USER SVC_SQL [AdminTo]", desc: "💡 IT सपोर्ट SVC_SQL सेवा खाते का प्रबंधन कर सकता है। लक्ष्य पुष्ट!" } ] }, terms: [ { name: "Service Account", desc: "स्वचालित कार्यों के लिए सिस्टम या एप्लिकेशन द्वारा उपयोग किया जाने वाला खाता — अक्सर खराब प्रबंधित।" }, { name: "Domain Admin", desc: "डोमेन में सभी कंप्यूटर और सर्वर को नियंत्रित करने वाला सर्वोच्च व्यवस्थापक विशेषाधिकार।" } ] },
      { title: "Kerberoasting", feynman: "हैकर बेधड़क पहरेदार के पास जाता है: 'मुझे रोबोट पहरेदार से बात करने का पास चाहिए।' यह वैध प्रक्रिया है, इसलिए सभी धोखा खा जाते हैं।", expert: "Kerberos TGS अनुरोध एक सामान्य प्रमाणीकरण प्रक्रिया है, इसलिए यह फ़ायरवॉल से बिना पकड़े गुज़र जाती है।", defTooltip: "⚠️ Event ID 4769: इस उपयोगकर्ता को असामान्य सेवा टिकट (TGS) जारी किया गया।", hackerLog: { title: "kerberoast_request.txt", lines: [ { log: "[*] Action: Kerberoasting", desc: "💡 SVC_SQL से संवाद के लिए केंद्रीय सर्वर से 'वैध पास' का अनुरोध।" }, { log: "[*] Target User : SVC_SQL", desc: "💡 कमज़ोर खाते को सटीक रूप से निशाना बनाकर सर्वर को धोखा दे रहा है।" } ] }, terms: [ { name: "Kerberoasting", desc: "कमज़ोर सेवा खातों के प्रमाणीकरण टिकट गुप्त रूप से प्राप्त कर ऑफ़लाइन पासवर्ड क्रैक करने की हमला तकनीक।" }, { name: "TGS (Ticket Granting Service)", desc: "किसी विशिष्ट सेवा तक पहुँच अधिकृत करने वाला वैध टिकट।" } ] },
      { title: "टिकट निकाला गया", feynman: "पहरेदार एक बंद तिजोरी (पास) सौंपता है। इसके अंदर रोबोट पहरेदार का असली पासवर्ड एन्क्रिप्टेड रूप में छिपा है।", expert: "सेवा खाते के NTLM हैश से एन्क्रिप्ट किया गया TGS टिकट मेमोरी से सफलतापूर्वक निकाला गया।", defTooltip: "📦 सर्वर ने वैध प्रमाणीकरण टिकट जारी किया। अभी तक कोई स्पष्ट दुर्भावनापूर्ण गतिविधि नहीं।", hackerLog: { title: "hash_extracted.txt", lines: [ { log: "[+] Ticket successfully extracted!", desc: "💡 सर्वर ने बिना किसी संदेह के एन्क्रिप्टेड टिकट सौंप दिया।" }, { log: "[+] Hash: $krb5tgs$23$*SVC_SQL$...", desc: "💡 लक्ष्य खाते का असली पासवर्ड इस हैश वैल्यू में छिपा है।" } ] }, terms: [ { name: "NTLM Hash", desc: "विंडोज द्वारा उपयोगकर्ता पासवर्ड को सुरक्षित रखने के लिए उपयोग किया जाने वाला एन्क्रिप्टेड (हैश्ड) डेटा प्रारूप।" }, { name: "Memory Extraction", desc: "सुरक्षा उपकरणों से छिपकर सिस्टम मेमोरी (RAM) से एन्क्रिप्टेड क्रेडेंशियल चुराने की तकनीक।" } ] },
      { title: "ऑफ़लाइन क्रैकिंग", feynman: "हैकर तिजोरी को चुपके से अपने तहखाने में ले जाता है। कंपनी के कैमरों से दूर, सुपरकंप्यूटर से करोड़ों चाबियाँ आज़मा रहा है।", expert: "कॉर्पोरेट नेटवर्क के बाहर हैकर के निजी हार्डवेयर पर ब्रूट-फ़ोर्स — आंतरिक रूप से पूरी तरह अदृश्य।", defTooltip: "🔇 (पता लगाना असंभव) हैकर कॉर्पोरेट नेटवर्क के बाहर ऑफ़लाइन पासवर्ड क्रैक कर रहा है...", hackerLog: { title: "offline_cracking.txt", lines: [ { log: "Session..........: hashcat\nStatus...........: Running", desc: "💡 हैकर के शक्तिशाली GPU से चुराए गए हैश को क्रैक करना शुरू।" }, { log: "Speed.Dev.#1.....: 25000 kH/s", desc: "💡 प्रति सेकंड करोड़ों पासवर्ड संयोजन आज़मा रहा है। नेटवर्क से बाहर — पूरी तरह अदृश्य।" } ] }, terms: [ { name: "Hashcat", desc: "GPU कंप्यूटिंग शक्ति का उपयोग करके अत्यधिक गति से पासवर्ड हैश क्रैक करने वाला उपकरण।" }, { name: "Brute-force", desc: "पासवर्ड मिलने तक हर संभव अक्षर संयोजन आज़माते रहने वाला हमला।" } ] },
      { title: "पासवर्ड क्रैक हुआ", feynman: "खटाक! पहरेदार ने '1234' जैसा कमज़ोर ताला इस्तेमाल किया था, तिजोरी खुल गई। मास्टर चाबी अब हैकर के हाथ में है।", expert: "कमज़ोर पासवर्ड नीति का फ़ायदा उठाकर उच्च-विशेषाधिकार खाते के प्लेनटेक्स्ट क्रेडेंशियल प्राप्त किए।", defTooltip: "🔇 (पता लगाना असंभव) पासवर्ड क्रैक हो गया, लेकिन आंतरिक सिस्टम में कोई विफल लॉगिन लॉग नहीं।", hackerLog: { title: "cracked_password.txt", lines: [ { log: "$krb5tgs$23$*SVC_SQL$...:P@ssword123!", desc: "💡 बिंगो! लक्ष्य ने अनुमानित पासवर्ड इस्तेमाल किया — तिजोरी खुल गई।" }, { log: "[+] Cracking completed successfully.", desc: "💡 उच्च-विशेषाधिकार खाते का पासवर्ड पूरी तरह समझौता हो चुका है।" } ] }, terms: [ { name: "Plaintext Credential", desc: "अनएन्क्रिप्टेड पासवर्ड जिसे सीधे पढ़ा और सिस्टम लॉगिन के लिए उपयोग किया जा सकता है।" }, { name: "Password Complexity", desc: "बड़े-छोटे अक्षर, संख्या और विशेष वर्णों को मिलाने वाले सुरक्षा नियम।" } ] },
      { title: "डोमेन पर कब्ज़ा", feynman: "हैकर मास्टर चाबी से राजा के सिंहासन (Domain Controller) पर बैठ गया। अब इस किले का हर कंप्यूटर हैकर की मर्ज़ी से चलता है।", expert: "चुराए गए Domain Admin क्रेडेंशियल से WinRM के ज़रिए Domain Controller (DC) को रिमोट एक्सेस करके इंफ्रास्ट्रक्चर पर कब्ज़ा।", defTooltip: "🚨 गंभीर! सामान्य PC IP से Domain Controller (DC) पर Domain Admin रिमोट एक्सेस का प्रयास!", hackerLog: { title: "domain_takeover.txt", lines: [ { log: "[*] Connecting to 192.168.10.10 (DC01)", desc: "💡 क्रैक किए पासवर्ड से कंपनी के शीर्ष सर्वर — Domain Controller — को रिमोट एक्सेस।" }, { log: "[+] Successful login! Session established.", desc: "💡 लॉगिन सफल! कंपनी का हर PC और सर्वर अब हैकर के नियंत्रण में।" } ] }, terms: [ { name: "WinRM / evil-winrm", desc: "विंडोज रिमोट मैनेजमेंट प्रोटोकॉल का शोषण करके लक्ष्य सिस्टम पर रिमोट शेल खोलने वाला हैकिंग टूल।" }, { name: "Lateral Movement", desc: "हमलावर का प्रारंभिक अपहृत PC से नेटवर्क के अन्य सर्वरों और व्यवस्थापक कार्यस्थलों तक विस्तार।" } ] },
      { title: "रक्षा सक्रिय", feynman: "लेकिन किले का गुप्त निरीक्षक (GOTROOT) देख रहा था! जैसे ही हैकर सिंहासन पर पहुँचा, उसने फंदा फेंका — संचार काटा और घुसपैठिए को बाहर निकाला।", expert: "सुरक्षा निगरानी प्रणालियों ने लेटरल मूवमेंट का पता लगाया और रियल-टाइम में फ़ायरवॉल IP ब्लॉकिंग और खाता निष्क्रियण किया।", defTooltip: "🛡️ स्वचालित रक्षा सक्रिय: हमलावर के IP को पूरी तरह ब्लॉक और आइसोलेट करने के लिए फ़ायरवॉल नीतियाँ अपडेट।", hackerLog: { title: "connection_terminated.txt", lines: [ { log: "FATAL ERROR: Connection forcefully closed", desc: "💡 रक्षा प्रणाली (EDR/SIEM) ने असामान्य व्यवहार का पता लगाया और तुरंत कनेक्शन समाप्त किया।" }, { log: "IP 192.168.10.45 has been isolated.", desc: "💡 संक्रमित PC को नेटवर्क से पूरी तरह आइसोलेट किया गया। रक्षा सफल!" } ] }, terms: [ { name: "EDR & SIEM", desc: "एंडपॉइंट खतरों का पता लगाने वाला समाधान (EDR) और सुरक्षा लॉग को एकत्र और सह-संबद्ध करने वाली केंद्रीय प्रणाली (SIEM)।" }, { name: "Network Isolation", desc: "संक्रमित PC की नेटवर्क पहुँच को जबरन काटकर मैलवेयर को अन्य आंतरिक सिस्टम में फैलने से रोकना।" } ] }
    ]
  },
  zh: {
    langCode: 'zh-CN',
    ui: {
      configTitle: "模拟环境设置", configSub: "信息将同步到终端环境。", userLabel: "受害者姓名", corpLabel: "目标公司名称", startBtn: "开始训练",
      hackerView: "💻 受害者 PC", defenderView: "🛡️ 防御者 SOC", step1: "👤 渗透", step2: "🔍 侦察", step3: "🔑 窃取", step4: "👑 控制",
      what: "场景说明", why: "专家见解", termsLabel: "核心术语和工具", complete: "训练完成 🎉", resetBtn: "重新开始", socTitle: "🛡️ SOC 实时警报", downloadCert: "下载 PDF 证书",
      state0: "正在渗透...", stateWaitTTS: "语音播放中...", statePlay: (t) => `下一步还有 ${t}秒。`, statePause: "已暂停",
      completeMsg: (u, c) => `恭喜 ${u}！您已成功保护 ${c} 基础设施。`, topoMap: "横向移动追踪",
      cert: { title: "结业证书", subtitle: "兹证明", desc: "已成功完成高级威胁模拟与防御训练模块：", date: "颁发日期", instructor: "首席讲师" },
      warning: "⚠️ 警告：本训练仅供安全教育目的使用。对任何滥用行为，用户须承担全部法律责任。",
      agreeText: "我同意上述法律声明。"
    },
    texts: [
      { title: "初始访问", feynman: "员工不经意间打开的一封钓鱼邮件，就像打开城门的开关。恶意程序运行，黑客的远程控制终端就此悄然开启。", expert: "通过鱼叉式钓鱼邮件实现 Initial Access。C2 服务器连接已建立。", defTooltip: "👀 检测到来自未知外部 IP 的远程访问流量。", hackerLog: null, terms: [{name:"Spear Phishing", desc:"针对特定目标的定向钓鱼邮件攻击。"}, {name:"C2 Server", desc:"攻击者用于远程控制受感染系统的中央服务器。"}] },
      { title: "初始渗透", feynman: "入侵者照了照镜子。'我现在穿的是平民的衣服还是将军的盔甲？'他要搞清楚自己当前的权限等级。", expert: "识别被入侵会话的权限级别和组成员身份，以制定权限提升策略。", defTooltip: "⚠️ 普通用户执行了可疑命令 (whoami /all) 查询系统权限。", hackerLog: { title: "whoami_priv_check.txt", lines: [ { log: "USER INFORMATION\n----------------\nUser Name: CORP\\Alice", desc: "💡 确认被盗账户的身份信息。" }, { log: "GROUP INFORMATION\n...\nBUILTIN\\Users", desc: "💡 查看组成员身份以确定访问范围。" }, { log: "PRIVILEGES INFORMATION\n...\nSeChangeNotifyPrivilege", desc: "💡 寻找可利用的权限来提升至管理员。" } ] }, terms: [ { name: "whoami /all", desc: "Windows命令，显示当前用户的账户名、所属组和所有分配的权限。" }, { name: "Privilege Escalation", desc: "将普通用户权限提升至系统最高管理员权限的黑客攻击阶段。" } ] },
      { title: "内网侦察", feynman: "要攻城掠寨，首先需要地图。黑客拿出指南针和地图，确认国王（中央服务器）城堡的位置。", expert: "识别子网范围和DNS（通常是域控制器）IP，以绘制目标网络拓扑。", defTooltip: "🔍 检测到网络扫描行为——正在探测内网IP和DNS服务器信息。", hackerLog: { title: "network_recon.txt", lines: [ { log: "IPv4 Address. . . . . . : 192.168.10.45", desc: "💡 受害者PC在企业网络中的内部IP地址。" }, { log: "Default Gateway . . . . : 192.168.10.1", desc: "💡 发现网关——通向外部网络的出口。" }, { log: "DNS Servers . . . . . . : 192.168.10.10", desc: "💡 企业网络中DNS服务器通常就是域控制器（国王）。目标已发现！" } ] }, terms: [ { name: "ipconfig /all", desc: "显示PC的IP、网关、DNS服务器等所有网络配置信息的命令。" }, { name: "Domain Controller", desc: "集中管理公司网络中所有账户和权限的核心服务器（王座）。" } ] },
      { title: "攻击路径探索", feynman: "调查数万居民来制作族谱！寻找通往国王的最快最隐蔽的路径。", expert: "使用BloodHound可视化Active Directory中对象之间的权限关系（ACL、会话）。", defTooltip: "🚨 短时间内检测到大量Active Directory信息查询（LDAP）！", hackerLog: { title: "SharpHound_Log_Analyzer.txt", lines: [ { log: "[+] Enumerating trusts for domain...", desc: "💡 正在映射域系统之间的信任关系（权限链）。" }, { log: "[+] Collecting Local Admin, Sessions...", desc: "💡 收集所有PC上的本地管理员权限和登录会话（寻找跳板）。" }, { log: "[+] Found 1500 Computers, 500 Users.", desc: "💡 完整的组织架构图和基础设施权限地图已获取！" }, { log: "[+] Compressing data to BloodHound.zip", desc: "💡 将庞大的权限地图压缩成一个zip文件准备外传。" } ] }, terms: [ { name: "SharpHound.exe", desc: "扫描域内数千台PC和用户之间所有权限关系（AD）的侦察工具。" }, { name: "BloodHound", desc: "利用收集的数据绘制到Domain Admin最短攻击路径的可视化工具。" } ] },
      { title: "目标锁定", feynman: "阿喀琉斯之踵被发现了！机器人守卫（服务账户）不小心随身携带着万能钥匙。", expert: "发现了一个密码长期未更改且拥有过高权限（Domain Admin）的服务账户。", defTooltip: "🎯 正在监控针对脆弱服务账户的异常访问模式。", hackerLog: { title: "attack_path_analysis.txt", lines: [ { log: "Node 1: USER Alice@corp.local", desc: "💡 我们当前的立足点——Alice被入侵的PC。" }, { log: "Node 2: GROUP IT_Support [MemberOf]", desc: "💡 发现Alice属于IT支持组——一条权限链。" }, { log: "Node 3: USER SVC_SQL [AdminTo]", desc: "💡 IT支持组可以管理SVC_SQL服务账户。目标确认！" } ] }, terms: [ { name: "Service Account", desc: "系统或应用程序用于自动化任务的账户——通常管理不善容易被忽视。" }, { name: "Domain Admin", desc: "可以控制域中所有计算机和服务器的最高管理员权限。" } ] },
      { title: "Kerberoasting", feynman: "黑客大摇大摆地走向守卫：'嘿，我需要一张通行证去跟机器人守卫说话。'这是合法程序，所以所有人都上当了。", expert: "Kerberos TGS请求是正常的认证流程，因此可以不被检测地通过现有防火墙。", defTooltip: "⚠️ Event ID 4769：该用户获得了异常的服务票据（TGS）。", hackerLog: { title: "kerberoast_request.txt", lines: [ { log: "[*] Action: Kerberoasting", desc: "💡 向中央服务器请求与SVC_SQL通信的'合法通行证'。" }, { log: "[*] Target User : SVC_SQL", desc: "💡 精准瞄准脆弱账户来欺骗服务器。" } ] }, terms: [ { name: "Kerberoasting", desc: "秘密获取脆弱服务账户的认证票据并离线破解密码的攻击技术。" }, { name: "TGS (Ticket Granting Service)", desc: "证明访问特定服务授权的合法票据。" } ] },
      { title: "票据窃取", feynman: "守卫交出一个上锁的保险箱（通行证）。里面藏着机器人守卫的真实密码——以加密形式。", expert: "成功从内存中提取了使用服务账户NTLM哈希加密的TGS票据。", defTooltip: "📦 服务器签发了合法的认证票据。目前尚无明显恶意行为迹象。", hackerLog: { title: "hash_extracted.txt", lines: [ { log: "[+] Ticket successfully extracted!", desc: "💡 服务器毫无怀疑地交出了加密票据。" }, { log: "[+] Hash: $krb5tgs$23$*SVC_SQL$...", desc: "💡 目标账户的真实密码就隐藏在这个哈希值中。" } ] }, terms: [ { name: "NTLM Hash", desc: "Windows用于存储和保护用户密码的加密（哈希）数据格式。" }, { name: "Memory Extraction", desc: "直接访问系统内存（RAM）秘密窃取加密凭证的技术。" } ] },
      { title: "离线破解", feynman: "黑客把保险箱偷偷带回自己的地下室。远离公司的监控摄像头，用超级计算机尝试数亿把钥匙。", expert: "在黑客私人设备上进行暴力破解——在企业网络之外，内部完全无法检测。", defTooltip: "🔇 （无法检测）黑客正在企业网络外部离线破解密码...", hackerLog: { title: "offline_cracking.txt", lines: [ { log: "Session..........: hashcat\nStatus...........: Running", desc: "💡 开始用黑客强大的GPU破解窃取的哈希。" }, { log: "Speed.Dev.#1.....: 25000 kH/s", desc: "💡 每秒尝试数千万个密码组合。在网络外部——完全无法检测。" } ] }, terms: [ { name: "Hashcat", desc: "利用GPU计算能力以极高速度破解密码哈希的工具。" }, { name: "Brute-force", desc: "不断尝试所有可能的字符组合直到密码被破解的攻击方式。" } ] },
      { title: "密码破解完成", feynman: "咔嗒！守卫用的是'1234'这样的简单锁，保险箱轻松打开。万能钥匙现在在黑客手中。", expert: "利用弱密码策略的漏洞获取了高权限账户的明文凭证。", defTooltip: "🔇 （无法检测）密码已被破解，但内部系统中没有任何登录失败日志。", hackerLog: { title: "cracked_password.txt", lines: [ { log: "$krb5tgs$23$*SVC_SQL$...:P@ssword123!", desc: "💡 中了！目标使用了可预测的密码——保险箱已打开。" }, { log: "[+] Cracking completed successfully.", desc: "💡 高权限账户的密码已被完全破解。" } ] }, terms: [ { name: "Plaintext Credential", desc: "未加密的密码，可以直接读取并用于登录系统。" }, { name: "Password Complexity", desc: "强制混合大小写字母、数字和特殊字符以抵御破解的安全规则。" } ] },
      { title: "域控制权夺取", feynman: "黑客用万能钥匙坐上了国王的宝座（域控制器）。现在城堡里的每台电脑都听从黑客的指挥。", expert: "使用窃取的Domain Admin凭证通过WinRM远程访问域控制器（DC），夺取基础设施完全控制权。", defTooltip: "🚨 严重警报！检测到从普通PC IP向域控制器（DC）发起的Domain Admin远程访问！", hackerLog: { title: "domain_takeover.txt", lines: [ { log: "[*] Connecting to 192.168.10.10 (DC01)", desc: "💡 使用破解的密码远程访问公司顶级服务器——域控制器。" }, { log: "[+] Successful login! Session established.", desc: "💡 登录成功！公司的每台PC和服务器现在都在黑客掌控之下。" } ] }, terms: [ { name: "WinRM / evil-winrm", desc: "利用Windows远程管理协议在目标系统上打开远程Shell的黑客工具。" }, { name: "Lateral Movement", desc: "攻击者从最初被入侵的PC扩展到网络中其他服务器和管理员工作站的过程。" } ] },
      { title: "防御启动", feynman: "但城堡的秘密巡查官（GOTROOT）一直在监视！就在黑客要坐上宝座的那一刻，他抛出绳索——切断通信，将入侵者驱逐出去。", expert: "安全监控系统检测到横向移动，实时执行了防火墙IP封锁和账户停用措施。", defTooltip: "🛡️ 自动防御启动：防火墙策略已更新，攻击者IP已被完全封锁和隔离。", hackerLog: { title: "connection_terminated.txt", lines: [ { log: "FATAL ERROR: Connection forcefully closed", desc: "💡 防御系统（EDR/SIEM）检测到异常行为并立即终止了连接。" }, { log: "IP 192.168.10.45 has been isolated.", desc: "💡 受感染PC已从网络中完全隔离。防御成功！" } ] }, terms: [ { name: "EDR & SIEM", desc: "检测终端威胁的解决方案（EDR）和集中聚合分析企业安全日志的中央系统（SIEM）。" }, { name: "Network Isolation", desc: "强制切断受感染PC的网络访问以防止恶意软件传播到其他内部系统。" } ] }
    ]
  },
  ja: {
    langCode: 'ja-JP',
    ui: {
      configTitle: "シミュレーション設定", configSub: "入力情報がターミナル環境に同期されます。", userLabel: "被害者名", corpLabel: "対象企業名", startBtn: "訓練を開始",
      hackerView: "💻 被害者 PC", defenderView: "🛡️ 防御者 SOC", step1: "👤 侵入", step2: "🔍 偵察", step3: "🔑 窃取", step4: "👑 制圧",
      what: "状況説明", why: "専門家の見解", termsLabel: "主要用語とツール", complete: "訓練完了 🎉", resetBtn: "リセット", socTitle: "🛡️ SOC リアルタイムアラート", downloadCert: "修了証 PDF ダウンロード",
      state0: "侵入演出中...", stateWaitTTS: "音声再生中...", statePlay: (t) => `次のステップまで ${t}秒...`, statePause: "一時停止中",
      completeMsg: (u, c) => `${u}さん、${c} のインフラ防御訓練を修了しました。`, topoMap: "ラテラルムーブメント追跡",
      cert: { title: "修 了 証", subtitle: "証明対象:", desc: "上記の者は、高度な脅威シミュレーション及び防御訓練課程を優秀な成績で修了しました。", date: "発行日", instructor: "主任インストラクター" },
      warning: "⚠️ 警告：本訓練に含まれるハッキングツール及び技法は、セキュリティ教育・防御訓練の目的のみに提供されます。不正利用の責任はすべて利用者にあります。",
      agreeText: "上記の法的告知および責任の所在を完全に理解し、これに同意します。"
    },
    texts: [
      { title: "事件の発端", feynman: "社員が何気なく開いたフィッシングメール1通が、城門を開くスイッチでした。マルウェアが実行され、ハッカーのリモートターミナルが静かに起動します。", expert: "スピアフィッシングによる Initial Access。C2 サーバーへの接続が確立されました。", defTooltip: "👀 バックグラウンドで不明な外部IPからのリモートアクセストラフィックが検出されました。", hackerLog: null, terms: [{name:"Spear Phishing", desc:"特定の対象に悪意のある添付ファイルやリンクを送る標的型メール攻撃。"}, {name:"C2 Server", desc:"攻撃者が感染したPCをリモートで制御するための中央制御サーバー。"}] },
      { title: "初期侵入", feynman: "侵入者が鏡を見ます。『今の自分は平民の服か、将軍の鎧か？』現在の権限レベルを把握するのです。", expert: "侵害されたセッションの特権レベルとグループメンバーシップを識別し、権限昇格戦略を立案します。", defTooltip: "⚠️ 一般ユーザーが不審なコマンド（whoami /all）でシステム権限を照会しました。", hackerLog: { title: "whoami_priv_check.txt", lines: [ { log: "USER INFORMATION\n----------------\nUser Name: CORP\\Alice", desc: "💡 乗っ取ったアカウントの身元を確認中。" }, { log: "GROUP INFORMATION\n...\nBUILTIN\\Users", desc: "💡 グループメンバーシップを確認してアクセス範囲を判断。" }, { log: "PRIVILEGES INFORMATION\n...\nSeChangeNotifyPrivilege", desc: "💡 管理者に昇格するために悪用できる特権を探索中。" } ] }, terms: [ { name: "whoami /all", desc: "現在のユーザーのアカウント名、所属グループ、すべての権限を表示するWindowsコマンド。" }, { name: "Privilege Escalation", desc: "一般ユーザー権限をシステム最高管理者権限に昇格させるハッキング段階。" } ] },
      { title: "内部ネットワーク偵察", feynman: "城を攻めるには地図が必要です。ハッカーがコンパスと地図を取り出し、王（中央サーバー）の城の位置を確認します。", expert: "サブネット範囲とDNS（通常はドメインコントローラー）のIPを特定し、ターゲットのネットワーク構成を把握します。", defTooltip: "🔍 内部IPとDNSサーバー情報を探索するネットワークスキャンの兆候を検出。", hackerLog: { title: "network_recon.txt", lines: [ { log: "IPv4 Address. . . . . . : 192.168.10.45", desc: "💡 被害者PCの社内ネットワーク上の内部IPアドレス。" }, { log: "Default Gateway . . . . : 192.168.10.1", desc: "💡 ネットワークの出口であるゲートウェイを発見。" }, { log: "DNS Servers . . . . . . : 192.168.10.10", desc: "💡 社内ネットワークのDNSサーバーは通常ドメインコントローラー（王）。ターゲット発見！" } ] }, terms: [ { name: "ipconfig /all", desc: "PCのIP、ゲートウェイ、DNSサーバーなど全ネットワーク設定を表示するコマンド。" }, { name: "Domain Controller", desc: "社内ネットワークの全アカウントと権限を中央管理するコアサーバー（王座）。" } ] },
      { title: "攻撃経路の探索", feynman: "数万人の住民を調査して家系図を作成！王に到達する最速かつ最も隠密なルートを探します。", expert: "BloodHoundを使用してActive Directory内のオブジェクト間の権限関係（ACL、セッション）を可視化します。", defTooltip: "🚨 短時間で大量のActive Directory情報照会（LDAP）が検出されました！", hackerLog: { title: "SharpHound_Log_Analyzer.txt", lines: [ { log: "[+] Enumerating trusts for domain...", desc: "💡 ドメインシステム間の信頼関係（権限チェーン）をマッピング中。" }, { log: "[+] Collecting Local Admin, Sessions...", desc: "💡 全PCのローカル管理者権限とログインセッションを収集（踏み台を探索）。" }, { log: "[+] Found 1500 Computers, 500 Users.", desc: "💡 組織全体の構成図とインフラ権限マップの取得完了！" }, { log: "[+] Compressing data to BloodHound.zip", desc: "💡 巨大な権限マップを一つのzipファイルに圧縮して持ち出し準備。" } ] }, terms: [ { name: "SharpHound.exe", desc: "ドメイン内の数千台のPCとユーザー間の権限関係（AD）を一掃収集する偵察ツール。" }, { name: "BloodHound", desc: "収集データからDomain Adminまでの最短攻撃経路を描画する可視化ツール。" } ] },
      { title: "ターゲット特定", feynman: "アキレス腱を発見！ロボット門番（サービスアカウント）がうっかりマスターキーを携帯していました。", expert: "パスワードが長期間変更されず、過剰な権限（Domain Admin）を持つサービスアカウントを特定。", defTooltip: "🎯 脆弱なサービスアカウントに対する異常なアクセスパターンを監視中。", hackerLog: { title: "attack_path_analysis.txt", lines: [ { log: "Node 1: USER Alice@corp.local", desc: "💡 現在の足場 ─ Aliceの侵害済みPC。" }, { log: "Node 2: GROUP IT_Support [MemberOf]", desc: "💡 AliceがITサポートグループに所属していることを発見 ─ 権限のリンク。" }, { log: "Node 3: USER SVC_SQL [AdminTo]", desc: "💡 ITサポートがSVC_SQLサービスアカウントを管理できることを確認。ターゲット確定！" } ] }, terms: [ { name: "Service Account", desc: "自動化タスクのためにシステムやアプリケーションが使用するアカウント ─ 管理がおろそかになりがち。" }, { name: "Domain Admin", desc: "ドメイン内のすべてのコンピューターとサーバーを制御できる最高管理者権限。" } ] },
      { title: "Kerberoasting", feynman: "ハッカーが堂々と門番に近づきます。「ロボット門番と話すためのパスをくれ」。正規の手続きなので、誰もが騙されます。", expert: "Kerberos TGSリクエストは正規の認証プロセスであるため、既存のファイアウォールを検知されずに通過できます。", defTooltip: "⚠️ Event ID 4769：このユーザーに異常なサービスチケット（TGS）が発行されました。", hackerLog: { title: "kerberoast_request.txt", lines: [ { log: "[*] Action: Kerberoasting", desc: "💡 SVC_SQLとの通信のため中央サーバーに「正規のパス」を要求中。" }, { log: "[*] Target User : SVC_SQL", desc: "💡 脆弱なアカウントを正確に狙ってサーバーを欺いています。" } ] }, terms: [ { name: "Kerberoasting", desc: "脆弱なサービスアカウントの認証チケットを密かに取得し、オフラインでパスワードを解析する攻撃手法。" }, { name: "TGS (Ticket Granting Service)", desc: "特定のサービスへのアクセス権限を証明する正規のチケット。" } ] },
      { title: "チケット窃取", feynman: "門番が施錠された金庫（パス）を渡します。中にはロボット門番の本当のパスワードが暗号化されて入っています。", expert: "サービスアカウントのNTLMハッシュで暗号化されたTGSチケットをメモリから成功裏に抽出しました。", defTooltip: "📦 サーバーが正規の認証チケットを発行。まだ明確な悪意ある活動の兆候はありません。", hackerLog: { title: "hash_extracted.txt", lines: [ { log: "[+] Ticket successfully extracted!", desc: "💡 サーバーが疑うことなく暗号化チケットを渡しました。" }, { log: "[+] Hash: $krb5tgs$23$*SVC_SQL$...", desc: "💡 ターゲットアカウントの本当のパスワードがこのハッシュ値の中に隠されています。" } ] }, terms: [ { name: "NTLM Hash", desc: "ユーザーのパスワードを保護するためにWindowsが使用する暗号化（ハッシュ）データ形式。" }, { name: "Memory Extraction", desc: "セキュリティツールに気づかれずにシステムメモリ（RAM）から暗号化された認証情報を窃取する技法。" } ] },
      { title: "オフラインクラッキング", feynman: "ハッカーが金庫を自宅の地下室にこっそり持ち帰ります。社内の監視カメラから離れ、スパコンで数億の鍵を次々と試します。", expert: "社内ネットワーク外のハッカーの個人機器でブルートフォース攻撃を実行 ─ 内部では完全に検知不可能。", defTooltip: "🔇 （検知不可）ハッカーが社内ネットワーク外でオフラインパスワード解析中...", hackerLog: { title: "offline_cracking.txt", lines: [ { log: "Session..........: hashcat\nStatus...........: Running", desc: "💡 ハッカーの強力なGPUで窃取したハッシュの解析を開始。" }, { log: "Speed.Dev.#1.....: 25000 kH/s", desc: "💡 毎秒数千万のパスワード組み合わせを試行中。ネットワーク外 ─ 完全に検知不可能。" } ] }, terms: [ { name: "Hashcat", desc: "GPUの演算能力を活用して極めて高速にパスワードハッシュを解析するツール。" }, { name: "Brute-force", desc: "パスワードが解かれるまで全ての可能な文字の組み合わせを試し続ける攻撃。" } ] },
      { title: "パスワード解読完了", feynman: "カチッ！門番が「1234」のような脆弱な鍵を使っていたため、金庫が開きました。マスターキーはハッカーの手に。", expert: "弱いパスワードポリシーの隙を突き、高権限アカウントの平文認証情報を取得しました。", defTooltip: "🔇 （検知不可）パスワードは解読されたが、内部システムにログイン失敗のログは一切残っていない。", hackerLog: { title: "cracked_password.txt", lines: [ { log: "$krb5tgs$23$*SVC_SQL$...:P@ssword123!", desc: "💡 ビンゴ！ターゲットが予測可能なパスワードを使用 ─ 金庫が開きました。" }, { log: "[+] Cracking completed successfully.", desc: "💡 高権限アカウントのパスワードが完全に漏洩しました。" } ] }, terms: [ { name: "Plaintext Credential", desc: "暗号化されておらず、そのまま読み取ってシステムログインに使用できるパスワード。" }, { name: "Password Complexity", desc: "大文字・小文字・数字・特殊文字の混合を強制して解析への耐性を高めるセキュリティルール。" } ] },
      { title: "ドメイン掌握", feynman: "ハッカーがマスターキーで王の玉座（ドメインコントローラー）に座りました。今やこの城のすべてのコンピューターがハッカーの意のままです。", expert: "窃取したDomain Admin認証情報でWinRMを介してドメインコントローラー（DC）にリモートアクセスし、インフラを完全に掌握。", defTooltip: "🚨 重大！一般PC IPからドメインコントローラー（DC）へのDomain Adminリモートアクセス試行を検出！", hackerLog: { title: "domain_takeover.txt", lines: [ { log: "[*] Connecting to 192.168.10.10 (DC01)", desc: "💡 解読したパスワードで会社最上位のサーバー ─ ドメインコントローラーにリモート接続。" }, { log: "[+] Successful login! Session established.", desc: "💡 ログイン成功！会社のすべてのPCとサーバーがハッカーの支配下に。" } ] }, terms: [ { name: "WinRM / evil-winrm", desc: "Windowsリモート管理プロトコルを悪用してターゲットシステムにリモートシェルを開くハッキングツール。" }, { name: "Lateral Movement", desc: "攻撃者が最初に侵害したPCからネットワーク内の他のサーバーや管理者端末へ侵入を拡大する行為。" } ] },
      { title: "防御発動", feynman: "しかし城の隠密検察官（GOTROOT）が見ていました！ハッカーが玉座に手を伸ばした瞬間、縄を投げて通信を切断し、侵入者を追い出します。", expert: "セキュリティ監視システムがラテラルムーブメントを検知し、リアルタイムでファイアウォールIP遮断とアカウント無効化を実施。", defTooltip: "🛡️ 自動防御発動：ファイアウォールポリシーを更新し、攻撃者のIPを完全にブロック・隔離。", hackerLog: { title: "connection_terminated.txt", lines: [ { log: "FATAL ERROR: Connection forcefully closed", desc: "💡 防御システム（EDR/SIEM）が異常行動を検知し即座に接続を強制終了。" }, { log: "IP 192.168.10.45 has been isolated.", desc: "💡 感染したPCがネットワークから完全に隔離されました。防御成功！" } ] }, terms: [ { name: "EDR & SIEM", desc: "エンドポイント脅威を検知するソリューション（EDR）と企業全体のセキュリティログを集約・相関分析する中央システム（SIEM）。" }, { name: "Network Isolation", desc: "感染PCのネットワークアクセスを強制的に切断し、マルウェアが他の内部システムに拡散するのを防止する措置。" } ] }
    ]
  },
};
