server {
    listen 80;
    server_name _;

    add_header X-Service edge-proxy always;
    add_header X-Orion-Demo "solarwinds-inspired-supply-chain" always;

    location / {
        proxy_pass http://public-site:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /docs/ {
        proxy_pass http://public-docs:8000/;
        proxy_set_header Host $host;
    }

    location /support/ {
        proxy_pass http://support-portal:8000/;
        proxy_set_header Host $host;
    }
}
